[package]
name = "hello_cargo"
version = "0.2.0"
authors = ["tkhm <devtkhm@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gotham = "0.4.0"
hyper = "0.13.1"
mime = "0.3.14"

